# coding:utf-8
# 图片验证码有效期
IMAGE_CODE_REDIS_EXPIRES = 180
# 短信验证码有效期
SMS_CODE_REDIS_EXPIRES = 300

SEND_SMS_CODE_INTERVAL = 60

LOGIN_ERROR_MAX_TIMES = 3

LOGIN_ERROR_FORBID_TIME = 300

QINIU_URL_DOMAIN = "http://o91qujnqh.bkt.clouddn.com/"

AREA_INFO_REDIS_CACHE_EXPIRES = 7200

HOME_PAGE_MAX_HOUSES = 5

HOME_PAGE_DATA_REDIS_EXPIRES = 7200

HOUSE_DETAIL_COMMENT_DISPLAY_COUNTS = 30

HOUSE_DETAIL_REDIS_EXPIRE_SECOND = 7200

HOUSE_LIST_PAGE_CAPACITY = 5

HOUES_LIST_PAGE_REDIS_CACHE_EXPIRES = 7200

ALIPAY_URL_PREFIX = "https://openapi.alipaydev.com/gateway.do?"
